create schema coordenacao;

CREATE TABLE coordenacao.dimensionamento (
	sistema text NULL,
	tipo text NULL,
	funcionario text NULL,
	equipe text NULL,
	modulo text NULL,
	papel text NULL,
	sustentacao text NULL,
	projeto text NULL
);

insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rosângela','SIGAA','Extensão','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rosângela','SIEC 2 Eventos','','Sistema-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rosângela','SIEC 1','','Legado','Sistemas Acadêmicos','Analista','NÃO','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rosângela','App RU UFG','','Aplicativo','Sistemas Acadêmicos','Gerente de Projeto','NÃO','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Edson','SP','','Legado','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Edson','SISP','','Legado','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Edson','Analisa','Acompanhamento Individual','Sistema-UFG','Sistemas de Recursos Humanos','Analista','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Edson','SIGRH','','SIG-UFG','Sistemas de Recursos Humanos','Coordenador','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Edson','SIGAdmin','','SIG-UFG','Sistemas de Recursos Humanos','Coordenador','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Edson','SIGEleições','','SIG-UFG','Sistemas de Recursos Humanos','Coordenador','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Edson','SISCONCURSO','','Sistema-UFG','Sistemas de Recursos Humanos','Coordenador','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Edson','SAD','','Sistema-UFG','Sistemas de Recursos Humanos','Coordenador','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Edson','Weby','','Sistema-UFG','Sistemas de Recursos Humanos','Coordenador','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Micael','SEI','','Sistema-UFG','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Micael','SIGEleições','','SIG-UFG','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Micael','SIGRH','Cadastro','SIG-UFG','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Micael','Novo SICAD','','Sistema-UFG','Sistemas de Recursos Humanos','Analista','NÃO','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Micael','Alocação de Vagas','','Sistema-UFG','Sistemas de Recursos Humanos','Gerente de Projeto','NÃO','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Micael','SIGRH','Frequência','SIG-UFG','Sistemas de Recursos Humanos','Analista','NÃO','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dione','SIGAdmin','','SIG-UFG','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dione','Weby','','Sistema-UFG','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dione','Portal UFGNet','','Sistema-UFG','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dione','Crachá','','Sistema-UFG','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dione','App RU UFG','','Aplicativo','Sistemas de Recursos Humanos','Analista','NÃO','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dione','Aplicativo CS Candidato','','Aplicativo','Sistemas de Recursos Humanos','Analista','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Bruno','SIGRH','Aposentadoria','SIG-UFG','Sistemas de Recursos Humanos','Analista','NÃO','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Bruno','SIGRH','Férias','SIG-UFG','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Bruno','SIGRH','Capacitação','SIG-UFG','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Bruno','SIGRH','Concursos','SIG-UFG','Sistemas de Recursos Humanos','Analista','NÃO','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Bruno','SIGRH','Comissões','SIG-UFG','Sistemas de Recursos Humanos','Analista','NÃO','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Bruno','SIGRH','Banco de Vagas','SIG-UFG','Sistemas de Recursos Humanos','Analista','NÃO','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Bruno','SISCONCURSO','','Sistema-UFG','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Bruno','Projeto UFG Aberta','Portal de Integração','Sistema-UFG','Sistemas de Recursos Humanos','Analista','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Bruno','Projeto UFG Aberta','Dados Abertos','Sistema-UFG','Sistemas de Recursos Humanos','Analista','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Clecio','SIGRH','Colegiados','SIG-UFG','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Clecio','SIGRH','Dimensionamento','SIG-UFG','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Clecio','SIGRH','Portaria','SIG-UFG','Sistemas de Recursos Humanos','Analista','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Clecio','SIGRH','Financeirto','SIG-UFG','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Clecio','SIGRH','Auxilios e Serviços','SIG-UFG','Sistemas de Recursos Humanos','Analista','NÃO','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Clecio','SAD','','Sistema-UFG','Sistemas de Recursos Humanos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Clecio','Resoluções','','Legado','Sistemas de Recursos Humanos','Analista','NÃO','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Clecio','Alocação de Vagas','','Sistema-UFG','Sistemas de Recursos Humanos','Analista','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Maria Dalva','SIGAA','Stricto Sensu','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Maria Dalva','SIGAA','Residência','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Maria Dalva','SICAD','','Legado','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Maria Dalva','SISPG SS','','Legado','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Maria Dalva','SISPG LS','','Legado','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Maria Dalva','SISPG COREMU','','Legado','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Maria Dalva','SISPG COREME','','Legado','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Romeu','SIGAA','','SIG-UFG','Sistemas Acadêmicos','Coordenador','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Vinícius','SIGAA','Graduação','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Vinícius','SIGAA','Lato Sensu','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Vinícius','SIGAA','Turma Virtual','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rogério Fiúza','SIGAA','NEE','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rogério Fiúza','SIGAA','Monitoria','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rogério Fiúza','SIGAA','Assistência ao Estudante','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rogério Fiúza','SIGAA','Ouvidoria','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rogério Pires','SIGAA','Pesquisa','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rogério Pires','SIGAA','Produção Intelectual','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rogério Pires','SIGAA','Diploma','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rogério Pires','SAP','','Legado','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rogério Pires','SICT','','Legado','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rogério Pires','SISCEPAE','','Legado','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rogério Pires','SARED-SRD','','Legado','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rogério Pires','Avaliador Lattes','','Sistema-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rogério Pires','SIGAA','Projeto de Ensino','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rogério Pires','Ello','','Sistema-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Matheus','SIGAA','Central de Estágios','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Matheus','SIGAA','Infantil','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Matheus','SIGAA','Fundamental','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Matheus','SIGAA','Médio','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Matheus','SIGAA','EAD','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Matheus','SISPPC','','Sistema-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('João Marcos','SIGAA','Processo Seletivo','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('João Marcos','SIGAA','Censo Extrator e Validador','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('João Marcos','SIGAA','Censo Discente e Docente','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('João Marcos','SAG','','Sistema-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('João Marcos','SAA','','Sistema-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('João Marcos','SAC','','Sistema-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('João Marcos','SEI','','Sistema-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Flávio','SIGAA','Graduação','SIG-UFG','Sistemas Acadêmicos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Lygia','SIPAC','','SIG-UFG','Sistemas Administrativos','Coordenador','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Lygia','SIGFOR','','Sistema-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Lygia','GRU Biblioteca','','Sistema-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Renata','SIPAC','Contratos','SIG-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Renata','SIPAC','Auditoria e Controle Interno','SIG-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Renata','Novo SISPAG','','Sistema-UFG','Sistemas Administrativos','Analista','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Renata','Projeto com Regionais','','Sistema-UFG','Sistemas Administrativos','Analista','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Malba','SIPAC','Bolsas','SIG-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Malba','SIPAC','Projetos e Convênios','SIG-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Malba','SIPAC','Protocolo','SIG-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Malba','Aplicativo CS Candidato','','Aplicativo','Sistemas Administrativos','Gerente de Projeto','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Malba','Aplicativo Patrimônio','','Aplicativo','Sistemas Administrativos','Gerente de Projeto','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Gil','SIPAC','Compras','SIG-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Gil','SIPAC','Registro de Preço','SIG-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Gil','SIPAC','Licitação','SIG-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Gil','Solicite','','Sistema-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Gil','Novo GRU','','Sistema-UFG','Sistemas Administrativos','Analista','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Jeová','SIPAC','Integração SIAFI','SIG-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Jeová','SIPAC','Orçamento','SIG-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Jeová','SIPAC','Patrimônio','SIG-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Jeová','MOSP','','Legado','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Jeová','SOS','','Legado','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Jeová','SCC','','Legado','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Jeová','SISGRU','','Legado','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Jeová','SISPAG','','Legado','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Claudivan','SIPAC','Auditoria e Controle Interno','SIG-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Claudivan','SIPAC','Transporte','SIG-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Claudivan','Projeto com Regionais','','Sistema-UFG','Sistemas Administrativos','Analista','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Claudivan','Aplicativo CS Candidato','','Aplicativo','Sistemas Administrativos','Analista','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Claudivan','Aplicativo Patrimônio','','Aplicativo','Sistemas Administrativos','Analista','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Andrey','Desenvolvimento','','Sistema-UFG','Desenvolvimento','Coordenador','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dannyel','SIGAA','Graduação','SIG-UFG','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dannyel','SIGAA','Censo Extrator','SIG-UFG','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dannyel','SISFOR','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dannyel','SISPG SS','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dannyel','SISPG LS','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dannyel','SISPG COREME','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dannyel','SISPG COREMU','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dannyel','SISPAG','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dannyel','SICAD','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dannyel','SOS','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dannyel','SCC','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dannyel','SOLICITE','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dannyel','mais 12 legados','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Dannyel','SEI','','Sistema-UFG','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Italo','Novo SISGRU','','Sistema-UFG','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Sílvio','Desenvolvimento','','Sistema-UFG','Desenvolvimento','Desenvolvedor','NÃO','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Jhonny','SARED-SRD','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Jhonny','Sisconcurso','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Jhonny','SISGRU','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Jhonny','SIEC 2','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Jhonny','Novo SICAD','','Sistema-UFG','Desenvolvimento','Desenvolvedor','NÃO','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Jhonny','Projeto UFG Aberta','Dados Abertos','Sistema-UFG','Desenvolvimento','Desenvolvedor','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Paulo','SARED-SRD','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Paulo','Sisconcurso','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Paulo','SISGRU','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Paulo','SIEC 2','','Legado','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Clecio','SIGRH','Consultas Funcionais','SIG-UFG','Sistemas de Recursos Humanos','Analista','NÃO','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Clecio','SIGRH','Financeiro','SIG-UFG','Sistemas de Recursos Humanos','Analista','NÃO','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Telmo','SIGRH','Portaria','SIG-UFG','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Nilson','SIGRH','Portaria','SIG-UFG','Desenvolvimento','Desenvolvedor','SIM','NÃO');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Marina','GrayLog','','Sistema-UFG','Desenvolvimento','Desenvolvedor','NÃO','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Ricardo','Novo SICAD','','Sistema-UFG','Desenvolvimento','Desenvolvedor','NÃO','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Ricardo','Projeto UFG Aberta','Dados Abertos','Sistema-UFG','Desenvolvimento','Desenvolvedor','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Felipe','Teste','','Sistema-UFG','Equipe Testes','Tester','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Philpe','Teste','','Sistema-UFG','Equipe Testes','Tester','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Guilherme','Teste','','Sistema-UFG','Equipe Testes','Tester','SIM','SIM');
insert into coordenacao.dimensionamento(funcionario,sistema, modulo, tipo, equipe, papel, sustentacao,projeto) values('Rosana','Teste','','Sistema-UFG','Equipe Testes','Tester','SIM','SIM');
